spring.application.name=summerproject.demo

spring.data.mongodb.uri=mongodb+srv://anikawpatil_db_user:1234@cluster0.xlauogq.mongodb.net/buggraveyard?retryWrites=true&w=majority&tls=true
spring.main.allow-circular-references=true